name: endeavor

services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres_user']
      interval: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/root/redis

  flyway:
    # Flyway Docker image: https://hub.docker.com/r/flyway/flyway
    container_name: flyway
    image: flyway/flyway:11-alpine
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/postgres_db
      FLYWAY_USER: postgres_user
      FLYWAY_PASSWORD: postgres_password
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    # Migrate: https://documentation.red-gate.com/fd/migrate-277578887.html
    # Environments Namespace: https://documentation.red-gate.com/fd/environments-namespace-277578909.html
    command: migrate
    volumes:
      - ../database/migrations:/flyway/sql
    restart: 'no'

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin_default_email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_default_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pgadmin4/preferences.json:/pgadmin4/preferences.json
    ports:
      - 5433:80

volumes:
  postgres_data:
  pgadmin_data:
  redis:
