name: endeavor

services:
  postgres:
    container_name: postgres
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U superuser']
      interval: 5s
      retries: 5
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis:/root/redis
    ports:
      - '6379:6379'
    restart: always

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.5
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - ./pgadmin4/preferences.json:/pgadmin4/preferences.json
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin_default_email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_default_password
    ports:
      - 5433:80
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/misc/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always

volumes:
  postgres_data:
  redis:
  pgadmin_data:
